test:unordered_map multi_map atomic

unordered_map:unordered_map.cpp
		g++ -std=c++11 -o unordered_map unordered_map.cpp 

multi_map:multi_map.cpp
		g++ -std=c++11 -o multi_map multi_map.cpp 

atomic:atomic.cpp
		g++ -std=c++11 -pthread -o atomic atomic.cpp 


clean:
		rm -f unordered_map multi_map atomic
